config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "movies#index"

  resources :movies do
  	member do
  		get :theaters
  	end
  end

  resources :bookings do
    member do
      get :book_ticket
    end
    collection do
      post :ticket_checkout
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
	belongs_to :movie_screen
end

app/models/movie.rb
class Movie < ApplicationRecord
	has_many :movie_screens
	has_many :screens, through: :movie_screens
	has_many :theaters, through: :screens


	enum movie_type: { english: 0, hindi: 1}
	scope :available_movies, -> { where(movie_status: 0) }
end

app/models/movie_screen.rb
class MovieScreen < ApplicationRecord
	belongs_to :movie
	belongs_to :screen
	has_many :bookings
end

app/models/screen.rb
class Screen < ApplicationRecord
	has_many :movie_screens
	belongs_to :theater
end

app/models/screen_show_time.rb
class ScreenShowTime < ApplicationRecord
	belongs_to :screen
	belongs_to :movie
end

app/models/theater.rb
class Theater < ApplicationRecord
	has_many :screens
	has_many :movie_screens, through: :screens
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  enum gender: { male: 'M', female: 'F', other: 'O'}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  before_action :devise_configure_permitted_parameters, if: :devise_controller?
  after_action :store_action
  
  def store_action
    return unless request.get? 
    if (request.path != "/users/sign_in" &&
        request.path != "/users/sign_up" &&
        request.path != "/users/password/new" &&
        request.path != "/users/password/edit" &&
        request.path != "/users/confirmation" &&
        request.path != "/users/sign_out" &&
        !request.xhr?) # don't store ajax calls
      store_location_for(:user, request.fullpath)
    end
  end

  # def after_sign_in_path_for(resource)
  # 	# redirect_to request.referer if request.referer
  # 	# request.referer
  # end

  protected

  def devise_configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :gender, :password)}
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

	def index
		@bookings = Booking.all.where(user_id: current_user.id)
	end

	def book_ticket
		if user_signed_in?
			@bookings = Booking.all.where(user_id: current_user.id)
			@booking_details = MovieScreen.find(params[:id])
		end
	end

	def ticket_checkout	
		movie_screen = MovieScreen.find(params[:movie_screen_id])
		data = {'status' => 'success'}
		booking_hash = {}
		booking_hash[:user_id ] = current_user.id
		booking_hash[:movie_screen_id ] = params[:movie_screen_id]
		booking_hash[:booked_seats ] = params[:booked_seats]
		booking_hash[:amount ] = params[:amount]
		booking = Booking.new(booking_hash)

		if booking.valid?
			booking.save!
			movie_screen.available_seats -= params[:booked_seats].to_i
			movie_screen.save!
		else
			data = {'status' => 'failure'}
		end		
	 	render json: data
	end

	def destroy
		booking = Booking.find(params[:id])
		movie_screen = booking.movie_screen
		movie_screen.available_seats += booking.booked_seats
		movie_screen.save!
		booking.destroy
		redirect_to bookings_url
	end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
	def index
		@movies = Movie.available_movies.order('release_date')
	end

	def theaters
		@movie = Movie.find(params[:id])
		@theaters = Theater.includes([screens: [:movie_screens]]).all
		@date = params[:date].present? ? Date.strptime(params[:date], '%m/%d/%Y') : Date.today
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookings/_bookings.html.erb
<div class="container py-3">
  <div class="row border border-primary">
    <div class="col-lg-12 col-md-12 col-sm-12">
      <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Movie</th>
            <th scope="col">Theater</th>
            <th scope="col">Show Timing</th>
            <th scope="col">Booked Seats</th>
            <th scope="col">Action</th>
          </tr>
        </thead>
        <tbody>
          <% @bookings.each_with_index do |booking, index| 
            movie_screen = booking.movie_screen
          %>
            <tr>
              <th scope="row"><%= index + 1 %></th>
              <td><%= movie_screen.movie.try(:name) %></td>
              <td>
                <%= movie_screen.screen.theater.try(:name) %>
                <span>|</span>
                <span>
                  <%= movie_screen.screen.theater.try(:landmark) %>
                </span>
                <span>
                  <%= movie_screen.screen.theater.try(:city) %>
                </span>
              </td>
              <td>
                <%= movie_screen.show_date %>
                <span>|</span>
                <%= movie_screen.show_time.strftime("%H:%M %p") %>  
              </td>
              <td><%= booking.booked_seats %></td>
              <td>
                <% if ((movie_screen.show_date.to_date <= Date.today) && (movie_screen.show_time.strftime("%H.%M").to_f < Time.now.strftime("%H.%M").to_f))  %>
                  <button type="button" class="btn btn-primary" disabled>
                    Cancel
                  </button>
                <% else %>
                  <%= button_to 'Cancel', booking_path(booking),class: "btn btn-outline-primary", method: :delete,data: { confirm: 'Are you sure?'} %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/bookings/book_ticket.html.erb
<div class="container py-3">
  <div class="row border border-primary">
    <div class="col-lg-12 col-md-12 col-sm-12">
      <h3 class="display-6">
        <%= @booking_details.movie.try(:name) %>
      </h3>
      <p class="text-muted">
        <span>
          <%= @booking_details.movie.movie_type.humanize.capitalize %>
        </span>
        <span>|</span>
        <span" >
          <%= @booking_details.show_date %>
        </span>
        <span>|</span>
        <span id="movie_screen" movie_screen_id="<%= @booking_details.id %>" >
          <%= @booking_details.show_time.strftime("%H:%M %p") %>
        </span>
      </p>
    </div>
  </div>
</div>

<div class="container">
	<div class="row">
    <div class="col-md-8 order-md-8 mb-8 pull-right">
      <%= render 'bookings' %>
    </div>
    <div class="col-md-4 order-md-2 mb-4">
      <ul class="list-group mb-3">
        <li class="list-group-item d-flex justify-content-between lh-condensed">
          <div>
            <h6 class="my-0 text-muted">Ticket Price</h6>
          </div>
          <span class="text-muted" id="ticket_price"><%= @booking_details.ticket_price %></span>
        </li>
        <li class="list-group-item d-flex justify-content-between lh-condensed">
          <div>
            <h6 class="my-0 text-muted">Available Seats</h6>
          </div>
          <span class="text-muted" id="available_seats"><%= @booking_details.available_seats %></span>
        </li>
        <li class="list-group-item d-flex justify-content-between lh-condensed">
          <div>
            <h6 class="my-0 text-muted">Selected Seats</h6>
          </div>
          <span class="text-muted">
          	<select id="selected_seats" onchange="calTotalPrice();">
          		<% (0..@booking_details.available_seats).each do |seat| %>
          		<option value="<%= seat %>"><%= seat %></option>
          		<% end %>
          	</select>
        </span>
        </li>
        <li class="list-group-item d-flex justify-content-between bg-light">
          <div class="text-success">
            <h6 class="my-0">Gender Discout</h6>
          </div>
          <span class="text-success" id="gender_discout" type="<%= current_user.gender %>">0</span>
        </li>
        <li class="list-group-item d-flex justify-content-between bg-light">
          <div class="text-success">
            <h6 class="my-0">Promo code</h6>
          </div>
          <span class="text-success" id="coupon_price">0</span>
        </li>
        <li class="list-group-item d-flex justify-content-between">
          <span class="text-muted">Total Price</span>
          <strong class="text-muted" id="total_price">0</strong>
        </li>
      </ul>

      <form class="card p-2">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Promo code">
          <div class="input-group-append">
            <button type="submit" class="btn btn-secondary">Redeem</button>
          </div>
        </div>
      </form>
      <hr class="mb-4">
      <button class="btn btn-primary btn-lg btn-block" type="button" onclick="bookTicket();">Book Ticket</button>
    </div>
  </div>
</div>

app/views/bookings/index.html.erb
<%= render 'bookings' %>

app/views/layouts/_alerts.html.erb
<!-- <p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p> -->

<!-- <div class="alert alert-success alert-dismissible fade show">
    <strong>Success!</strong> Your message has been sent successfully.
    <button type="button" class="close" data-dismiss="alert">&times;</button>
</div>

<div class="alert alert-danger alert-dismissible fade show">
    <strong>Error!</strong> A problem has been occurred while submitting your data.
    <button type="button" class="close" data-dismiss="alert">&times;</button>
</div>
 -->

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">BookMovieShows</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to 'Bookings', bookings_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
    <ul class="navbar-nav pull-right">
      <% if !user_signed_in? %>
        <li class="nav-item mr-2">          
            <%= link_to 'Register', new_user_registration_path,class: "btn btn-outline-primary" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Login', new_user_session_path,class: "btn btn-outline-primary" %>
        </li>
      <% else %>
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= current_user.try(:name) %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to 'Edit Accout', edit_user_registration_path(current_user.id), class: "dropdown-item" %>
          <%= link_to 'Logout', destroy_user_session_path, class: "dropdown-item",method: :delete %>
        </div>
      </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieBooking</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/movies/_theater_list.html.erb
<div class="container">
	<% @theaters.each do | theater | %>
		<div class="row border-bottom border-bottom border-dark">
		  <div class="col-lg-3 col-md-3 col-sm-3">
		    <div>
		    	<span>
		    		<%= theater.try(:name) %>
		    	</span>
		    	<p class="text-muted">
		    		<span>
		    		<%= theater.try(:street_name) %>
		    	</span>
		    	<span>
		    		<%= theater.try(:landmark) %>
		    	</span>
		    	<span>
		    		<%= theater.try(:city) %>
		    	</span>
		    	</p>
		    </div>
		  </div>
		  <div class="col-lg-9 col-md-9 col-sm-9">
		  	<div class="d-flex flex-row bd-highlight mb-3">
		  		<% movie_theaters = []%>
		  		<% theater.screens.each do |screen| %>
			    	<% screen.movie_screens.map{ |moviescreen| movie_theaters << moviescreen if moviescreen.movie_id == @movie.id and moviescreen.show_date == @date } %>
			    	<% movie_theaters.each do |movie_screen|%>
			    		<div class="p-2 bd-highlight">
			    			<% if user_signed_in? %>
			    			<% show_date = movie_screen.show_date %>
			    				<% if (movie_screen.show_time.strftime("%H.%M").to_f < Time.now.strftime("%H.%M").to_f) && (show_date == Date.today) %>
			    					<button type="button" class="btn btn-primary" disabled>
                  		<%= movie_screen.show_time.strftime("%H:%M %p") %>
                  	</button>
			    				<% elsif show_date > Date.today %>
			    					<%= button_to movie_screen.show_time.strftime("%H:%M %p"), book_ticket_booking_path(movie_screen.id), method: :get, class: "btn btn-primary" %> 
			    				<% else %>
			    					<%= button_to movie_screen.show_time.strftime("%H:%M %p"), book_ticket_booking_path(movie_screen.id), method: :get, class: "btn btn-primary" %> 
			    				<% end %>
			    			<% else %>
                  	<button type="button" class="btn btn-primary" disabled>
                  		<%= movie_screen.show_time.strftime("%H:%M %p") %>
                  	</button>
                 <% end %>
			    		</div>
			    	<% end %>
			    <% end %>
			  </div>
		  </div>
		</div>
	<% end %>
</div>

app/views/movies/index.html.erb
<div class="py-2">
  <div class="container">
    <% @movies.each_with_index do |movie, indx| %>
      <% if ((indx) % 3 == 0) %>
        <div class="row py-2">
      <% end %> 
      <div class="col-lg-4 col-md-4 col-sm-4">
        <a href="movies/<%= movie.id %>/theaters" class="movie-card">
          <div class="card bg-light" style="width: 18rem;">
            <div class="card-body">
              <h5 class="card-title"><%= movie.name %></h5>
              <h6 class="card-subtitle mb-2 text-muted">
                Language :
                <%= movie.movie_type.humanize.capitalize %>
              </h6>
              <h6 class="card-subtitle mb-2 text-muted">
                Release Date : 
                <%= movie.release_date.strftime("%m/%d/%Y") %>
              </h6>
            </div>
          </div>
        </a>
      </div>
      <% if ((indx+1) % 3 == 0) %>
          </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/movies/theaters.html.erb
<div class="container py-3">
	<div class="row border border-primary">
		<div class="col-lg-8 col-md-8 col-sm-8">
			<h3 class="display-6" id="movie_id" movie_id=<%= @movie.id %> >
				<%= @movie.try(:name) %>
			</h3>
			<p class="text-muted">
				<span><%= @movie.movie_type.humanize.capitalize %></span> |
				<span><%= @movie.release_date.strftime("%m/%d/%Y") %></span>
			</p>
		</div>
		<div class="col-lg-4 col-md-4 col-sm-4 py-3">
			<span class="text-muted">Booking Date :</span>
			<%= text_field_tag "datepicker",@date %>
		</div>
	</div>
</div>
<div id="theater_list">
<%= render partial: 'theater_list' %>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    $('#datepicker').datepicker({
    	startDate: '0'
    });

    $("#datepicker").change(function() {
    	var movie_id = $("#movie_id").attr("movie_id");
    	var date = $("#datepicker").val();
	    var current_location = window.location.href.split('?')[0]
	    window.location.href = current_location + "?date="+date;   	
		});
  });
</script>